/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\642ec6ea27074836a6a806b03a15ec5a.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Eve(props) {
  const { nodes, materials } = useGLTF('/642ec6ea27074836a6a806b03a15ec5a.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes._gltfNode_0.geometry} material={materials.Eve} />
      <mesh geometry={nodes._gltfNode_2.geometry} material={materials.Eve} />
      <mesh geometry={nodes._gltfNode_4.geometry} material={materials.Eve} />
      <mesh geometry={nodes._gltfNode_6.geometry} material={materials.Eve} />
      <mesh geometry={nodes._gltfNode_8.geometry} material={materials['Mat.2']} />
      <mesh geometry={nodes._gltfNode_10.geometry} material={materials.Mat} />
      <mesh geometry={nodes._gltfNode_12.geometry} material={materials.Mat} />
    </group>
  )
}

useGLTF.preload('/642ec6ea27074836a6a806b03a15ec5a.gltf')
